name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Store UID'
        id: uid
        run: echo id="$(id -u $USER)" >> $GITHUB_OUTPUT

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Checkout submodules'
        run: git submodule update --init --recursive --depth 1 --jobs "$(getconf _NPROCESSORS_ONLN)";

      - name: 'Setup python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"
          echo "event_type=$TYPE" >> $GITHUB_OUTPUT

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Install & Build Portal'
        run: |
          cd components/svelte-portal
          npm install
          npm run build

      - name: 'Build firmware'
        uses: Intake-Health/esp-idf-ci-action@release-v4.4

      - name: 'Make artifacts'
        run: |
          mkdir -p artifacts
          cp build/bootloader/bootloader.bin artifacts/
          cp build/partition_table/partition-table.bin artifacts/
          cp build/blackmagic.bin artifacts/
          cp scripts/flash_nix.sh artifacts/
          echo "esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32s2 write_flash $(tr '\n' ' ' < build/flash_args)" > artifacts/flash.command

      - name: 'Upload Firmware Ke Sini'
        uses: actions/upload-artifact@v4
        with:
          name: blackmagic-esp32s2-firmware
          path: artifacts/
